[package]
name = "async-dashscope"
version = "0.2.0"
edition = "2021"
description = "A Rust client for DashScope API"
repository = "https://github.com/kingzcheung/async-dashscope"
authors = ["kingzcheung <kingzcheung@gmail.com>"]
categories = ["api-bindings", "web-programming", "asynchronous"]
rust-version = "1.75"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kingzcheung/async-dashscope"

[dependencies]
derive_builder = "0.20.2"
reqwest-eventsource = "0.6.0"
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive", "rc"] }
serde_json = "1.0.135"
tracing = "0.1.41"
bytes = "1.9.0"
reqwest = { version = "0.12.12", features = [
  "json",
  "stream",
  "multipart",
], default-features = false }
secrecy = { version = "0.10.3", features = ["serde"] }
backoff = { version = "0.4.0", features = ["tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.13", features = ["codec", "io-util"] }

[features]
default = ["rustls"]
# Enable rustls for TLS support
rustls = ["reqwest/rustls-tls-native-roots"]

native-tls = ["reqwest/native-tls"]

[[example]]
name = "chat"
path = "examples/text-generation.rs"

[[example]]
name = "chat-stream"
path = "examples/text-generation-stream.rs"

[[example]]
name = "mt"
path = "examples/qwen-mt.rs"

[[example]]
name = "mt-stream"
path = "examples/qwen-mt-stream.rs"

[[example]]
name = "multimodal"
path = "examples/multimodal-generation.rs"

[[example]]
name = "multimodal-stream"
path = "examples/multimodal-generation-stream.rs"

[[example]]
name = "text-embedding"
path = "examples/text-embedding.rs"